Set-Variable CONST_MINUTE_IN_SECONDS -Option Constant -Value 60
Set-Variable CONST_HOUR_IN_SECONDS -Option Constant -Value 3600

Set-Variable CONST_ONE_MINUTE_IN_SECONDS -Option Constant -Value (1 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_TWO_MINUTES_IN_SECONDS -Option Constant -Value (2 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_THREE_MINUTES_IN_SECONDS -Option Constant -Value (3 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_FIVE_MINUTES_IN_SECONDS -Option Constant -Value (5 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_TEN_MINUTES_IN_SECONDS -Option Constant -Value (10 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_FIFTEEN_MINUTES_IN_SECONDS -Option Constant -Value (15 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_TWENTY_MINUTES_IN_SECONDS -Option Constant -Value (20 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_TWENTYFIVE_MINUTES_IN_SECONDS -Option Constant -Value (25 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_THIRTY_MINUTES_IN_SECONDS -Option Constant -Value (30 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_FORTYFIVE_MINUTES_IN_SECONDS -Option Constant -Value (45 * $CONST_MINUTE_IN_SECONDS)
Set-Variable CONST_ONE_CONST_HOUR_IN_SECONDS -Option Constant -Value (1 * $CONST_HOUR_IN_SECONDS)
Set-Variable CONST_TWO_HOURS_IN_SECONDS -Option Constant -Value (2 * $CONST_HOUR_IN_SECONDS)
Set-Variable CONST_THREE_HOURS_IN_SECONDS -Option Constant -Value (3 * $CONST_HOUR_IN_SECONDS)
Set-Variable CONST_FOUR_HOURS_IN_SECONDS -Option Constant -Value (4 * $CONST_HOUR_IN_SECONDS)
Set-Variable CONST_FIVE_HOURS_IN_SECONDS -Option Constant -Value (5 * $CONST_HOUR_IN_SECONDS)
